STUDENT
INSERT INTO STUDENT VALUES (student_seq.NEXTVAL, 'John', 'Doe', 'john@edu.co.za');
INSERT INTO STUDENT VALUES (student_seq.NEXTVAL, 'Jane', 'Smith', 'jane@edu.co.za');

INSTRUCTOR
INSERT INTO INSTRUCTOR VALUES (instructor_seq.NEXTVAL, 'Mr Moyo');
INSERT INTO INSTRUCTOR VALUES (instructor_seq.NEXTVAL, 'Ms Nkosi');

MODULE
INSERT INTO MODULE VALUES ('IT101', 'Introduction to IT', 1);
INSERT INTO MODULE VALUES ('CS102', 'Cyber Security Basics', 2);

REGISTRATION
INSERT INTO REGISTRATION VALUES (1, 'IT101');
INSERT INTO REGISTRATION VALUES (2, 'CS102');

SELECT * FROM STUDENT;
SELECT * FROM INSTRUCTOR;
SELECT * FROM MODULE;
SELECT * FROM REGISTRATION;
